version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: shoppinglist-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    image: ghcr.io/nagyrichard/shoppinglist-backend:latest
    container_name: shoppinglist-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      MongoDbSettings__ConnectionString: mongodb://mongodb:27017
      MongoDbSettings__DatabaseName: ShoppingListDb

  frontend:
    image: ghcr.io/nagyrichard/shoppinglist-frontend:latest
    container_name: shoppinglist-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mongodb_data: