name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for backend
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/shoppinglist-backend
          tags: |
            type=raw,value=latest
            type=sha

      - name: Extract metadata for frontend
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/shoppinglist-frontend
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./source/backend/ShoppingList.Api
          file: ./source/backend/ShoppingList.Api/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./source/frontend/shopping-list-ui
          file: ./source/frontend/shopping-list-ui/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}